AWSTemplateFormatVersion: '2010-09-09'
Description: >
  MERN App - ECS Fargate Backend Deployment
  ECS Cluster, Task Definition, Service, ALB, ECR Repository

Parameters:
  Environment:
    Type: String
    Default: production
  DockerImage:
    Type: String
    Description: Docker image URI (ECR)
    Default: "123456789.dkr.ecr.us-east-1.amazonaws.com/mern-backend:latest"
  VpcStackName:
    Type: String
    Description: Name of the VPC CloudFormation stack
    Default: mern-vpc-stack
  JwtSecret:
    Type: String
    NoEcho: true
    Description: JWT Secret key

Resources:
  # ─── ECR Repository ───────────────────────────────────────────────────────────
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "mern-backend-${Environment}"
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [{
              "rulePriority": 1,
              "description": "Keep last 10 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 10
              },
              "action": {"type": "expire"}
            }]
          }
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ─── ECS Cluster ─────────────────────────────────────────────────────────────
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "mern-cluster-${Environment}"
      CapacityProviders: [FARGATE, FARGATE_SPOT]
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 2
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  # ─── Secrets Manager for JWT ──────────────────────────────────────────────────
  JwtSecretParam:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/mern/${Environment}/jwt-secret"
      Description: JWT Secret for MERN backend
      SecretString: !Ref JwtSecret

  # ─── IAM Role for ECS Task Execution ─────────────────────────────────────────
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "mern-ecs-execution-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SecretsManagerRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref JwtSecretParam

  # ─── ECS Task Role ───────────────────────────────────────────────────────────
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "mern-ecs-task-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [s3:PutObject, s3:GetObject, s3:DeleteObject]
                Resource: !Sub "arn:aws:s3:::mern-uploads-${Environment}/*"

  # ─── CloudWatch Log Group ─────────────────────────────────────────────────────
  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/mern-backend-${Environment}"
      RetentionInDays: 30

  # ─── ECS Task Definition ─────────────────────────────────────────────────────
  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "mern-backend-${Environment}"
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: !Ref DockerImage
          PortMappings:
            - ContainerPort: 5000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: PORT
              Value: '5000'
          Secrets:
            - Name: JWT_SECRET
              ValueFrom: !Sub "${JwtSecretParam}:jwt_secret::"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: backend
          HealthCheck:
            Command: ["CMD-SHELL", "wget -qO- http://localhost:5000/health || exit 1"]
            Interval: 30
            Timeout: 10
            Retries: 3
            StartPeriod: 30
          Essential: true

  # ─── Application Load Balancer ────────────────────────────────────────────────
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "mern-alb-${Environment}"
      Scheme: internet-facing
      Type: application
      Subnets:
        - Fn::ImportValue: !Sub "${VpcStackName}-PublicSubnet1"
        - Fn::ImportValue: !Sub "${VpcStackName}-PublicSubnet2"
      SecurityGroups:
        - Fn::ImportValue: !Sub "${VpcStackName}-ALBSecurityGroup"

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "mern-tg-${Environment}"
      Port: 5000
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: !Sub "${VpcStackName}-VpcId"
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  # ─── ECS Service ─────────────────────────────────────────────────────────────
  BackendECSService:
    Type: AWS::ECS::Service
    DependsOn: ALBListener
    Properties:
      ServiceName: !Sub "mern-backend-service-${Environment}"
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref BackendTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${VpcStackName}-BackendSecurityGroup"
          Subnets:
            - Fn::ImportValue: !Sub "${VpcStackName}-PrivateSubnet1"
            - Fn::ImportValue: !Sub "${VpcStackName}-PrivateSubnet2"
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: 5000
          TargetGroupArn: !Ref ALBTargetGroup
      HealthCheckGracePeriodSeconds: 60

  # ─── Auto Scaling ─────────────────────────────────────────────────────────────
  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 2
      ResourceId: !Sub "service/${ECSCluster}/${BackendECSService.Name}"
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService"

  CPUScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: mern-cpu-scaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 70.0
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

Outputs:
  ECSClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${AWS::StackName}-ECSCluster"

  ALBDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-ALBDnsName"

  ECRRepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-ECRUri"
