AWSTemplateFormatVersion: '2010-09-09'
Description: >
  MERN App - Frontend Infrastructure
  S3 Static Hosting + CloudFront CDN + Route 53 DNS

Parameters:
  DomainName:
    Type: String
    Description: Your root domain (e.g., example.com)
    Default: example.com
  SubDomain:
    Type: String
    Description: Subdomain for the app (e.g., www or app)
    Default: www
  AcmCertificateArn:
    Type: String
    Description: ACM Certificate ARN (must be in us-east-1 for CloudFront)
  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Resources:
  # ─── S3 Bucket ──────────────────────────────────────────────────────────────
  FrontendBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${SubDomain}.${DomainName}-frontend-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: MERNApp

  # ─── CloudFront Origin Access Control ────────────────────────────────────────
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "mern-app-oac-${Environment}"
        Description: OAC for MERN App S3 bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # ─── S3 Bucket Policy (allow CloudFront only) ─────────────────────────────
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # ─── CloudFront Distribution ────────────────────────────────────────────────
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Sub "${SubDomain}.${DomainName}"
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03  # SecurityHeaders
        CustomErrorResponses:
          # SPA support: serve index.html for 404/403
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
        HttpVersion: http2and3
        IPV6Enabled: true
        Comment: !Sub "MERN App CloudFront - ${Environment}"
        PriceClass: PriceClass_100
        Logging:
          !If
            - IsProduction
            - Bucket: !GetAtt FrontendBucket.DomainName
              IncludeCookies: false
              Prefix: cloudfront-logs/
            - !Ref AWS::NoValue
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ─── Route 53 DNS Record ─────────────────────────────────────────────────────
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${SubDomain}.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront Hosted Zone ID (constant)
        EvaluateTargetHealth: false

  # ─── IPv6 Route 53 Record ─────────────────────────────────────────────────
  Route53RecordSetIPv6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${SubDomain}.${DomainName}"
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  BucketName:
    Description: S3 Bucket name for frontend deployment
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID (needed for cache invalidation)
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionId"

  CloudFrontURL:
    Description: CloudFront Distribution URL
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"

  WebsiteURL:
    Description: Website URL
    Value: !Sub "https://${SubDomain}.${DomainName}"
